name: Bug Report
description: Report a defect with clear reproduction steps and acceptance criteria
title: "bug: <short title>"
labels: ["type:bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Briefly describe the problem and its impact.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps To Reproduce
      description: List exact steps, inputs, and expected timing.
      placeholder: "1) ... 2) ... 3) ..."
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs/Screenshots
      description: Attach snippets, stack traces, or screenshots.
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      options:
        - local
        - staging
        - production
    validations:
      required: true
  - type: checkboxes
    id: acceptance
    attributes:
      label: Acceptance Criteria
      options:
        - label: Repro steps produce expected behavior
        - label: Regression tests added where applicable
        - label: No new ESLint/flake8 errors; build is green

