"""Initial baseline migration

Revision ID: 0ab192bd5eea
Revises: 
Create Date: 2025-07-05 19:35:56.144784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ab192bd5eea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE sync_details ALTER COLUMN direction TYPE syncdirection USING direction::syncdirection")
    op.execute("ALTER TABLE sync_details ALTER COLUMN sync_type TYPE synctype USING sync_type::synctype")
    op.execute("ALTER TABLE sync_details ALTER COLUMN status TYPE syncstatus USING status::syncstatus")
    op.create_index(op.f('ix_sync_details_user_id'), 'sync_details', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sync_details_user_id'), table_name='sync_details')
    op.alter_column('sync_details', 'status',
               existing_type=sa.Enum('SUCCESS', 'ERROR', name='syncstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('sync_details', 'sync_type',
               existing_type=sa.Enum('MANUAL', 'AUTOMATIC', name='synctype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('sync_details', 'direction',
               existing_type=sa.Enum('GMAIL_TO_EA', 'EA_TO_GMAIL', 'BI_DIRECTIONAL', name='syncdirection'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
