"""Check for model/schema discrepancies

Revision ID: 92cdd3d6b9f8
Revises: d4ad63c70b05
Create Date: 2025-07-05 19:37:29.853510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92cdd3d6b9f8'
down_revision: Union[str, Sequence[str], None] = 'd4ad63c70b05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
